#! /bin/sh
export PATH=$PATH:~/Scripts

# Startup
pgrep -x sxhkd > /dev/null || sxhkd &  
xrandr --dpi 115
picom &
nitrogen --restore &
light -I
pkill lxsession
lxsession &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
killall -q polybar && sleep 0.5
polybar mainbar -r & disown

bspc monitor -d I II III IV V VI VII VIII IX X

# Theme 
bspc config border_width         2
bspc config window_gap          10
bspc config focused_border_color "#d8dee9"
bspc config presel_feedback_color "#00c1d6"
bspc config normal_border_color "#3b4252"

# Settings
bspc config split_ratio			0.50
bspc config borderless_monocle		true
bspc config gapless_monocle		false
bspc config single_monocle		true
bspc config focus_follows_pointer	true
bspc config automatic_scheme 		"spiral"
bspc config initial_polarity		"first_child"

# Application Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a origin.exe state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a GLava border=off
bspc rule -a Steam state=floating
bspc rule -a Volume Control state=floating
bspc rule -a Pavucontrol state=floating


