#!/bin/bash

cd ~/ && cp -f .slstatus/config.h .zshrc .p10k.zsh .xinitrc ConfigBackup/Dot-Files/

cp -rf ~/.config/{dunst,qtile,picom,bspwm,sxhkd,polybar,kitty,ranger,neofetch,cava,helix} ~/ConfigBackup/Dot-Files/.config/

# Copy Xmonad Config
# cp -f .config/xmonad/xmonad.hs ~/ConfigBackup/Dot-Files/.xmonad/

# Copy Custom Rofi config and themes
cp -f /usr/share/rofi/themes/{customblue.rasi,customfullscreen.rasi,customnordfull.rasi} ~/ConfigBackup/Dot-Files/rofi/themes/ && cp -rf .config/rofi/ ConfigBackup/Dot-Files/.config/

# Copy DWM Config
cp -rf .dwm ConfigBackup/Dot-Files/
cp -rf .slsstatus/* ConfigBackup/Dot-Files/.slsstatus/

# Copy Scripts
cp -rf Scripts ConfigBackup/Dot-Files/

# Copy Grub Settings
cp /etc/default/grub ConfigBackup/Dot-Files/etc/default/

# Copy VIMRC
cp .vim/vimrc ConfigBackup/Dot-Files/etc/

# Copy ncmpcpp config
cp -rf .config/ncmpcpp ConfigBackup/Dot-Files/.config/
cp -rf .config/mpd ConfigBackup/Dot-Files/.config

# Push changes to Github
cd ConfigBackup/Dot-Files/ && git add . && git commit -m "update" && git push
