#!/usr/bin/env python

import sys
import os
argument = sys.argv
argument = argument[1:]

if argument == []:
    os.system("maim | tee ~/Pictures/$(date +%Y-%m-%d-%H%M)_screenshot.png | xclip -selection clipboard -t image/png")

elif argument[0] == "copy":
    os.system("maim | xclip -selection clipboard -t image/png")

elif argument[0] == "select":
    os.system("maim -s | tee ~/Pictures/$(date +%Y-%m-%d-%H%M)_screenshot.png | xclip -selection clipboard -t image/png")

elif argument[0] == "select-copy":
    os.system("maim -s | xclip -selection clipboard -t image/png")

elif argument[0] == "window":
    os.system("maim -u -i $(xdotool selectwindow) | tee ~/Pictures/$(date +%Y-%m-%d-%H%M)_screenshot.png | xclip -selection clipboard -t image/png")

elif argument[0] == "window-copy":
    os.system("maim -u -i $(xdotool selectwindow) | xclip -selection clipboard -t image/png")
